### ISSUE TITLE
Why the 20:404 offset in the image array?

### ISSUE THREAD

**Issue by uberMaximus** [neil454/deep-motion#6]
I am trying to work out any image pre-processing that was needed for the KITTI data, and wondered if there was any particular reason for the 20:404 array range?

Did you manually resize the images before ingesting or are you "cropping" the X array?

**Comment by neil454** [comment]
For others, @uberMaximus is referring to [this line](https://github.com/neil454/deep-motion/blob/master/src/data_generator.py#L229).

I believe it's because I wanted to train the network on images with a 16:9 aspect ratio (the standard aspect ratio for video these days), and I think the KITTI images are taken at a wider aspect ratio, so I just cropped the middle using some pre-calculated numbers.

**Comment by uberMaximus** [comment]
Ok, Thanks.
